meta:
  last_updated: 08-02-2026_12-00-00
  origin:
    latitude: 53.268642038
    longitude: -0.524509505881
    altitude: 0

metric_map: test_map
name: test_map
pointset: test_map

transformation:
  topological_frame_id: test_map
  parent: map
  rotation:
    w: 1.0
    x: 0.0
    y: 0.0
    z: 0.0
  translation:
    x: 0.0
    y: 0.0
    z: 0.0

definitions:
  default_bt: |
    <root main_tree_to_execute="MainTree">
      <BehaviorTree ID="MainTree">
        <RecoveryNode number_of_retries="0" name="NavigateRecovery">
          <PipelineSequence name="NavigateWithReplanning">
            <RateController hz="0.333">
              <RecoveryNode number_of_retries="0" name="ComputePathThroughPoses">
                <ReactiveSequence>
                  <RemovePassedGoals input_goals="{goals}" output_goals="{goals}" radius="1.5"/>
                  <ComputePathThroughPoses goals="{goals}" path="{path}" planner_id="GridBased"/>
                </ReactiveSequence>
                <ReactiveFallback name="ComputePathThroughPosesRecoveryFallback">
                  <GoalUpdated/>
                  <ClearEntireCostmap name="ClearGlobalCostmap-Context" service_name="global_costmap/clear_entirely_global_costmap"/>
                </ReactiveFallback>
              </RecoveryNode>
            </RateController>
            <RecoveryNode number_of_retries="0" name="FollowPath">
              <FollowPath path="{path}" controller_id="FollowPath"/>
              <ReactiveFallback name="FollowPathRecoveryFallback">
                <GoalUpdated/>
                <ClearEntireCostmap name="ClearLocalCostmap-Context" service_name="local_costmap/clear_entirely_local_costmap"/>
              </ReactiveFallback>
            </RecoveryNode>
          </PipelineSequence>
          <ReactiveFallback name="RecoveryFallback">
            <GoalUpdated/>
            <RoundRobin name="RecoveryActions">
              <Sequence name="ClearingActions">
                <ClearEntireCostmap name="ClearLocalCostmap-Subtree" service_name="local_costmap/clear_entirely_local_costmap"/>
                <ClearEntireCostmap name="ClearGlobalCostmap-Subtree" service_name="global_costmap/clear_entirely_global_costmap"/>
              </Sequence>
              <Spin spin_dist="1.57"/>
              <Wait wait_duration="5"/>
              <BackUp backup_dist="0.15" backup_speed="0.025"/>
            </RoundRobin>
          </ReactiveFallback>
        </RecoveryNode>
      </BehaviorTree>
    </root>
  goal_align_bt: |
    <root main_tree_to_execute="MainTree">
      <BehaviorTree ID="MainTree">
        <RecoveryNode number_of_retries="6" name="NavigateRecovery">
          <PipelineSequence name="NavigateWithReplanning">
            <RateController hz="1.0">
              <RecoveryNode number_of_retries="1" name="ComputePathToPose">
                <ComputePathToPose goal="{goal}" path="{path}" planner_id="GridBased"/>
                <ReactiveFallback name="ComputePathToPoseRecoveryFallback">
                  <GoalUpdated/>
                  <ClearEntireCostmap name="ClearGlobalCostmap-Context" service_name="global_costmap/clear_entirely_global_costmap"/>
                </ReactiveFallback>
              </RecoveryNode>
            </RateController>
            <RecoveryNode number_of_retries="1" name="FollowPath">
              <FollowPath path="{path}" controller_id="FollowPath"/>
              <ReactiveFallback name="FollowPathRecoveryFallback">
                <GoalUpdated/>
                <ClearEntireCostmap name="ClearLocalCostmap-Context" service_name="local_costmap/clear_entirely_local_costmap"/>
              </ReactiveFallback>
            </RecoveryNode>
          </PipelineSequence>
          <ReactiveFallback name="RecoveryFallback">
            <GoalUpdated/>
            <RoundRobin name="RecoveryActions">
              <Sequence name="ClearingActions">
                <ClearEntireCostmap name="ClearLocalCostmap-Subtree" service_name="local_costmap/clear_entirely_local_costmap"/>
                <ClearEntireCostmap name="ClearGlobalCostmap-Subtree" service_name="global_costmap/clear_entirely_global_costmap"/>
              </Sequence>
              <Wait wait_duration="5"/>
              <BackUp backup_dist="0.15" backup_speed="0.025"/>
            </RoundRobin>
          </ReactiveFallback>
        </RecoveryNode>
      </BehaviorTree>
    </root>
  row_traversal_bt: |
    <root main_tree_to_execute="MainTree">
      <BehaviorTree ID="MainTree">
        <RecoveryNode number_of_retries="0" name="NavigateRecovery">
          <PipelineSequence name="NavigateWithReplanning">
            <RateController hz="0.333">
              <RecoveryNode number_of_retries="0" name="ComputePathThroughPoses">
                <ReactiveSequence>
                  <RemovePassedGoals input_goals="{goals}" output_goals="{goals}" radius="1.5"/>
                  <ComputePathThroughPoses goals="{goals}" path="{path}" planner_id="GridBased"/>
                </ReactiveSequence>
                <ReactiveFallback name="ComputePathThroughPosesRecoveryFallback">
                  <GoalUpdated/>
                  <ClearEntireCostmap name="ClearGlobalCostmap-Context" service_name="global_costmap/clear_entirely_global_costmap"/>
                </ReactiveFallback>
              </RecoveryNode>
            </RateController>
            <RecoveryNode number_of_retries="0" name="FollowPath">
              <FollowPath path="{path}" controller_id="FollowPath"/>
              <ReactiveFallback name="FollowPathRecoveryFallback">
                <GoalUpdated/>
                <ClearEntireCostmap name="ClearLocalCostmap-Context" service_name="local_costmap/clear_entirely_local_costmap"/>
              </ReactiveFallback>
            </RecoveryNode>
          </PipelineSequence>
          <ReactiveFallback name="RecoveryFallback">
            <GoalUpdated/>
            <RoundRobin name="RecoveryActions">
              <Sequence name="ClearingActions">
                <ClearEntireCostmap name="ClearLocalCostmap-Subtree" service_name="local_costmap/clear_entirely_local_costmap"/>
                <ClearEntireCostmap name="ClearGlobalCostmap-Subtree" service_name="global_costmap/clear_entirely_global_costmap"/>
              </Sequence>
              <Wait wait_duration="5"/>
              <BackUp backup_dist="0.15" backup_speed="0.025"/>
            </RoundRobin>
          </ReactiveFallback>
        </RecoveryNode>
      </BehaviorTree>
    </root>

actions:
  navigate_to_pose:
    composable: false
    action_type: nav2_msgs/NavigateToPose
    action_server: /navigate_to_pose
    action_goal_template:
      pose: '${node.pose}'
      behavior_tree: '${definitions.default_bt}'
  navigate_to_pose_goal_align:
    composable: false
    action_type: nav2_msgs/NavigateToPose
    action_server: /navigate_to_pose
    action_goal_template:
      pose: '${node.pose}'
      behavior_tree: '${definitions.goal_align_bt}'
  row_traversal:
    composable: true
    action_type: nav2_msgs/NavigateThroughPoses
    action_server: /navigate_through_poses
    action_goal_template:
      poses: ['${node.pose}']
      behavior_tree: '${definitions.row_traversal_bt}'

nodes:
  - meta:
      map: test_map
      node: node0
      pointset: test_map
    node:
      edges:
        - action: row_traversal
          edge_id: node0_node1
          node: node1
      name: node0
      parent_frame: test_map
      pose:
        orientation:
          w: 1.0
          x: 0.0
          y: 0.0
          z: 0.0
        position:
          x: 0.0
          y: 0.0
          z: 0.0
      properties:
        xy_goal_tolerance: 0.3
        yaw_goal_tolerance: 6.28
      verts:
        - x: 0.3839717361251064
          y: -0.6411198818013286
        - x: 0.5264215248037732
          y: -0.212953957097135
        - x: 0.4432315207951729
          y: 0.3549856737865013
        - x: 0.1839678947585299
          y: 0.724309885809929
        - x: -0.3839717361251064
          y: 0.6411198818013286
        - x: -0.5264215248037732
          y: 0.212953957097135
        - x: -0.4432315207951729
          y: -0.3549856737865013
        - x: -0.1839678947585299
          y: -0.724309885809929

  - meta:
      map: test_map
      node: node1
      pointset: test_map
    node:
      edges:
        - action: row_traversal
          edge_id: node1_node2
          node: node2
      name: node1
      parent_frame: test_map
      pose:
        orientation:
          w: 1.0
          x: 0.0
          y: 0.0
          z: 0.0
        position:
          x: 2.0
          y: 0.0
          z: 0.0
      properties:
        xy_goal_tolerance: 0.3
        yaw_goal_tolerance: 6.28
      verts:
        - x: 0.3839717361251064
          y: -0.6411198818013286
        - x: 0.5264215248037732
          y: -0.212953957097135
        - x: 0.4432315207951729
          y: 0.3549856737865013
        - x: 0.1839678947585299
          y: 0.724309885809929
        - x: -0.3839717361251064
          y: 0.6411198818013286
        - x: -0.5264215248037732
          y: 0.212953957097135
        - x: -0.4432315207951729
          y: -0.3549856737865013
        - x: -0.1839678947585299
          y: -0.724309885809929

  - meta:
      map: test_map
      node: node2
      pointset: test_map
    node:
      edges:
        - action: row_traversal
          edge_id: node2_node3
          node: node3
      name: node2
      parent_frame: test_map
      pose:
        orientation:
          w: 1.0
          x: 0.0
          y: 0.0
          z: 0.0
        position:
          x: 4.0
          y: 0.0
          z: 0.0
      properties:
        xy_goal_tolerance: 0.3
        yaw_goal_tolerance: 6.28
      verts:
        - x: 0.3839717361251064
          y: -0.6411198818013286
        - x: 0.5264215248037732
          y: -0.212953957097135
        - x: 0.4432315207951729
          y: 0.3549856737865013
        - x: 0.1839678947585299
          y: 0.724309885809929
        - x: -0.3839717361251064
          y: 0.6411198818013286
        - x: -0.5264215248037732
          y: 0.212953957097135
        - x: -0.4432315207951729
          y: -0.3549856737865013
        - x: -0.1839678947585299
          y: -0.724309885809929

  - meta:
      map: test_map
      node: node3
      pointset: test_map
    node:
      edges:
        - action: row_traversal
          edge_id: node3_node4
          node: node4
      name: node3
      parent_frame: test_map
      pose:
        orientation:
          w: 1.0
          x: 0.0
          y: 0.0
          z: 0.0
        position:
          x: 6.0
          y: 0.0
          z: 0.0
      properties:
        xy_goal_tolerance: 0.3
        yaw_goal_tolerance: 6.28
      verts:
        - x: 0.3839717361251064
          y: -0.6411198818013286
        - x: 0.5264215248037732
          y: -0.212953957097135
        - x: 0.4432315207951729
          y: 0.3549856737865013
        - x: 0.1839678947585299
          y: 0.724309885809929
        - x: -0.3839717361251064
          y: 0.6411198818013286
        - x: -0.5264215248037732
          y: 0.212953957097135
        - x: -0.4432315207951729
          y: -0.3549856737865013
        - x: -0.1839678947585299
          y: -0.724309885809929

  - meta:
      map: test_map
      node: node4
      pointset: test_map
    node:
      edges: []
      name: node4
      parent_frame: test_map
      pose:
        orientation:
          w: 1.0
          x: 0.0
          y: 0.0
          z: 0.0
        position:
          x: 8.0
          y: 0.0
          z: 0.0
      properties:
        xy_goal_tolerance: 0.3
        yaw_goal_tolerance: 6.28
      verts:
        - x: 0.3839717361251064
          y: -0.6411198818013286
        - x: 0.5264215248037732
          y: -0.212953957097135
        - x: 0.4432315207951729
          y: 0.3549856737865013
        - x: 0.1839678947585299
          y: 0.724309885809929
        - x: -0.3839717361251064
          y: 0.6411198818013286
        - x: -0.5264215248037732
          y: 0.212953957097135
        - x: -0.4432315207951729
          y: -0.3549856737865013
        - x: -0.1839678947585299
          y: -0.724309885809929
